name: ecodeem
description: Ecodeem is a platform for eco friendly platform for social and economic growth
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_icons: ^2.0.0
  cuberto_bottom_bar: ^1.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.7
  flutter_svg: ^0.22.0
  get: ^4.1.4
  get_storage: ^2.0.2
  intl: ^0.17.0
  ionicons: ^0.1.2
  liquid_swipe: ^2.1.0
  local_auth: ^1.1.6
  persistent_bottom_nav_bar: ^4.0.2
  pinput: ^1.2.0
  sizer: ^2.0.13
  unicons: ^2.0.1
  url_launcher: ^6.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico/pacificoRegular.ttf
          weight: 400
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/latoThin.ttf
          weight: 100

        - asset: assets/fonts/lato/latoThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/lato/latoLight.ttf
          weight: 300

        - asset: assets/fonts/lato/latoLightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/lato/latoRegular.ttf
          weight: 400

        - asset: assets/fonts/lato/LatoItalic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/lato/LatoBold.ttf
          weight: 700

        - asset: assets/fonts/lato/latoBoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/lato/latoBlack.ttf
          weight: 900

        - asset: assets/fonts/lato/latoBlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/images/brand/
    - assets/images/design/
    - assets/images/collection/
    - assets/images/interests/
    - assets/images/icons/
